language: ruby
install: bundle install -j 4 --retry 3
script:
  - RAILS_ENV=test bundle exec rspec spec
services:
  - redis-server

matrix:
  include:
    - rvm: "2.3.0"
    - rvm: "2.3.3"
    - rvm: "2.4.1"
    - rvm: "2.5.7"
    - rvm: "2.6.5"
    - rvm: "2.7.2"
    - rvm: "3.0.0"
